export enum RedisConfigEnum {
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_DB = 'REDIS_DB',
}

export enum MongoDbConfigEnum {
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MONGODB_DATABASE = 'MONGODB_DATABASE',
  MONGODB_AUTH_SOURCE = 'MONGODB_AUTH_SOURCE',
}

export enum MongoDbUrlEnum {
  MONGODB_URL = 'MONGODB_URL',
}

export enum EmailConfigEnum {
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_AUTH_USER = 'EMAIL_AUTH_USER',
  EMAIL_AUTH_PASS = 'EMAIL_AUTH_PASS',
}

export enum OSSConfigEnum {
  OSS_ACCESS_KEY_ID = 'OSS_ACCESS_KEY_ID',
  OSS_ACCESS_KEY_SECRET = 'OSS_ACCESS_KEY_SECRET',
  OSS_ENDPOINT = 'OSS_ENDPOINT',
  OSS_REGION = 'OSS_REGION',
  OSS_BUCKET = 'OSS_BUCKET',
}

export enum MiNiOConfigEnum {
  MINIO_ENDPOINT = 'MINIO_ENDPOINT',
  MINIO_PORT = 'MINIO_PORT',
  MINIO_ACCESS_KEY = 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY = 'MINIO_SECRET_KEY',
  MINIO_BUCKET = 'MINIO_BUCKET',
}

export enum GitHubLoginConfigEnum {
  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CLIENT_URL = 'GITHUB_CLIENT_URL',
  GITHUB_USER_INFO_URL = 'GITHUB_USER_INFO_URL',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
}
