export enum SocketKeys {
  SINGLE_CHAT = 'SINGLE_CHAT', // 单聊
  GROUP_CHAT = 'GROUP_CHAT', // 群聊
  FRIEND_REQUEST_CREATED = 'FRIEND_REQUEST_CREATED', // 申请好友
  FRIEND_REQUEST_UPDATED = 'FRIEND_REQUEST_UPDATED', // 同意申请好友
  HEARTBEAT = 'HEARTBEAT', // 心跳检测
}
